//Joey Teahan - 20520316
//HistoryViewModel - These files were automatically generated by Android Studio
package com.example.multiway.ui.history

import androidx.lifecycle.ViewModel

class HistoryViewModel : ViewModel() {
    // TODO: Implement the ViewModel
}