//Joey Teahan - 20520316
//Account view model class, These files were automatically generated by Android Studio
package com.example.multiway.ui.account

import androidx.lifecycle.ViewModel

class CompanionViewModel : ViewModel() {
    // TODO: Implement the ViewModel
}