//Joey Teahan - 20520316
//EventsViewModel class, These files were automatically generated by Android Studio
package com.example.multiway.ui.events

import androidx.lifecycle.ViewModel

class SuggestedViewModel : ViewModel() {
    // TODO: Implement the ViewModel
}